# this is a convenience method to add systemd timers
#
# - name: do dummy timer
#   include_role:
#     name: basic-host
#     tasks_from: add_timer
#   vars:
#     systemd_timer_name: dummy-timer
#     systemd_timer_oncalendar: "*-*-* *:50:00"
#     systemd_timer_command: /bin/true

- set_fact:
    systemd_timers: >
      {{ {} | combine({
        systemd_timer_name: {
          'description': systemd_timer_description|default(systemd_timer_name),
          'oncalendar': systemd_timer_oncalendar,
          'command': systemd_timer_command|default('/bin/true'),
          'add_service': systemd_timer_add_service|default(True),
          'user': systemd_timer_user|default('root'),
          'randomized_delay_sec': systemd_timer_randomized_delay_sec|default(0),
        }
      })}}

- name: setup timer
  include_tasks: systemd_timer.yml
