- set_fact:
    selinux_module_dir: /tmp
  when: selinux_module_dir is undefined

# might be better not in tmp/without cleanup to avoid the reload delay
- name: copy type enforcement file
  copy:
    src: "{{item.key}}.te"
    dest: "/tmp/{{item.key}}.te"
    owner: root
    group: root
    mode: 0644
  register: te_copy_result

- name: compile selinux module
  command: checkmodule -M -m -o /tmp/{{item.key}}.mod /tmp/{{item.key}}.te
  when: te_copy_result is changed

- name: build selinux policy package
  command: semodule_package -o /tmp/{{item.key}}.pp -m /tmp/{{item.key}}.mod
  when: te_copy_result is changed

# at least modern selinux replaces packages. This may fail on older systems
- name: load/update selinux policy package
  command: semodule -i /tmp/{{item.key}}.pp

- name: remove temporary files
  file:
    path: /tmp/{{item.key}}.*
    state: absent
  when: selinux_module_dir == '/tmp'