# note: deletion of old certificates is currently not supported
- name: install additional CA certificates
  tags:
    - access_setup
  copy:
    src: "{{item}}"
    dest: "/etc/pki/ca-trust/source/anchors/{{item}}"
  with_items: "{{ca_certificates|default({})}}"

# this would be better tied to actually changing CA files, but handlers
# only run at the end, which would be too late here. Given that it returns
# very quickly it's not worth the effort to check for changes.
- name: refresh CA trust
  shell: /usr/bin/update-ca-trust
  tags:
    - access_setup
  changed_when: false

- set_fact:
    dist_token: ""
  tags:
    - access_setup

- name: set dist token {{ansible_distribution_major_version}}
  set_fact:
    dist_token: rhel7
  when:
    ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  tags:
    - access_setup

- set_fact:
    centos_repositories: {}
  when: centos_repositories is undefined
  tags:
    - access_setup

- set_fact:
    fedora_repositories: {}
  when: fedora_repositories is undefined
  tags:
    - access_setup

- set_fact:
    epel_repositories: {}
  when: epel_repositories is undefined
  tags:
    - access_setup

- set_fact:
    elrepo_repositories: {}
  when: elrepo_repositories is undefined
  tags:
    - access_setup

- set_fact:
    _sig_group_mappings:
      ansible26: configmanagement
      ansible27: configmanagement
      openstack-queens: cloud
      openstack-rocky: cloud
      openstack-stein: cloud
      ceph-jewel: storage
      ceph-nautilus: storage
      gluster-4.0: storage
      gluster-5: storage
      nfs-ganesha-28: storage
      ceph-luminous: storage
      gluster-3.12: storage
      gluster-4.1: storage
      gluster-6: storage
      sclo: sclo
      rh: sclo
  tags:
    - access_setup


# media, sources, vault and debuginfo repositories are not provided by us
# enabled repositories are configured through centos_repositories. Subkeys
# are:
#
# - plus
# - cr
# - fasttrack
# - sclo
# - sclo_rh
#
# example:
# centos_repositories
#   sclo: 1
#   sclo_rh: 1
- name: configure dist repos (CentOS)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-fasttrack.repo
#    - CentOS-SCLo-scl.repo
#    - CentOS-SCLo-scl-rh.repo
  when: ansible_distribution == "CentOS" and centos_mirror is defined
  tags:
    - access_setup

# available repository keys, the ones with asterisk are enabled per default:
# - fedora*
# - source
# - debuginfo
# - updates*
# - updates_source
# - updates_debuginfo
# - modular*
# - modular_source
# - modular_debuginfo
# - updates_modular*
# - updates_modular_source
# - updates_modular_debuginfo
# - updates_testing
# - updates_testing_source
# - updates_testing_debuginfo
# - updates_testing_modular
# - updates_testing_modular_source
# - updates_testing_modular_debuginfo

- name: configure dist repos (Fedora)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - fedora-modular.repo
    - fedora-updates-modular.repo
    - fedora-updates-testing-modular.repo
    - fedora-updates-testing.repo
    - fedora-updates.repo
    - fedora.repo
  when: ansible_distribution == "Fedora" and fedora_mirror is defined
  tags:
    - access_setup

- name: configure epel repos (CentOS)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - epel.repo
    - epel-testing.repo
  when: ansible_distribution == "CentOS" and epel_mirror is defined
  tags:
    - access_setup

- name: add epel repo key (CentOS)
  copy:
    src: "RPM-GPG-KEY-EPEL-7"
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    owner: root
    mode: 0644
  when: ansible_distribution == "CentOS" and epel_mirror is defined
  tags:
    - access_setup

- name: configure elrepo repos (CentOS)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - elrepo.repo
  when: ansible_distribution == "CentOS" and elrepo_mirror is defined
  tags:
    - access_setup

- name: add elrepo key (CentOS)
  copy:
    src: "RPM-GPG-KEY-elrepo.org"
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    owner: root
    mode: 0644
  when: ansible_distribution == "CentOS" and elrepo_mirror is defined
  tags:
    - access_setup

- name: configure fastest_mirror (CentOS)
  template:
    src: yum_fastestmirror.conf.j2
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    owner: root
    mode: 0644
  when: ansible_distribution == "CentOS" and centos_mirror is defined
  tags:
    - access_setup

- name: copy CentOS SIG keys
  copy:
    src: "{{item.value.gpgkey|default('RPM-GPG-KEY-CentOS-SIG-'+_sig_group_mappings[item.key]|capitalize)}}"
    dest: "/etc/pki/rpm-gpg/{{item.value.key|default('RPM-GPG-KEY-CentOS-SIG-'+_sig_group_mappings[item.key]|capitalize)}}"
    owner: root
    mode: 0644
  when: centos_sig_repositories is defined
  with_dict: "{{centos_sig_repositories}}"
  tags:
    - access_setup

- name: add CentOS SIG repositories
  template:
    src: "CentOS-SIG.repo.j2"
    dest: /etc/yum.repos.d/Centos-SIG.repo
    owner: root
    mode: 0644
  when: centos_sig_repositories is defined
  tags:
    - access_setup

- name: add additional RPM repositories
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/{{item.key}}.repo
    owner: root
    mode: 0644
  with_dict: "{{ rpm_repos }}"
  when: rpm_repos is defined
  tags:
    - access_setup

- name: add SPP repository (no token)
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/hp-spp.repo
    owner: root
    mode: 0644
  with_dict: { hp_spp: { baseurl: '{{hp_spp_repository}}', description: "HP SPP" }}
  when: >
    hp_spp_repository is defined and
    (hp_spp_append_dist is undefined or hp_spp_append_dist == False)
    and server_type is defined and server_type == "proliant"
  tags:
    - access_setup

- name: add SPP repository (dist token)
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/hp-spp.repo
    owner: root
    mode: 0644
  with_dict: { hp_spp: { baseurl: '{{hp_spp_repository}}/{{dist_token}}', description: "HP SPP" }}
  when: >
    hp_spp_repository is defined and
    (hp_spp_append_dist is defined and hp_spp_append_dist == True)
    and server_type is defined and server_type == "proliant"
  tags:
    - access_setup

- name: configure dnf
  template:
    src: dnf.conf.j2
    dest: /etc/dnf/dnf.conf
    owner: root
    mode: 0755
  tags:
    - access_setup
  when: >
    proxy_host is defined and skip_proxy is undefined
    and ansible_pkg_mgr == "dnf"

- name: configure python-firewall package (default)
  set_fact:
    python_firewall_package: python-firewall
  tags:
    - access_setup

- name: configure python-firewall package (Fedora >= 29)
  set_fact:
    python_firewall_package: python3-firewall
  when:
    ansible_distribution == 'Fedora' and ansible_distribution_version|int >= 29
  tags:
    - access_setup

- name: set HP SPP packages
  set_fact:
    hp_packages:
      - ssacli
      - ssaducli
#      - sut
      - hponcfg
      - hpdiags

- name: set basic packages
  set_fact:
    bare_metal_packages:
      - bridge-utils
      - dmidecode
      - hdparm
      - ipmitool
      - lm_sensors
      - lsof
      - lvm2
      - nmap
      - ntp
      - smartmontools
      - tcpdump
      - vconfig
    base_packages:
      - bash-completion
      - bzip2
      - ca-certificates
      - curl
      - firewalld
      - iotop
      - iperf
      - iproute
      - jq
      - fuse
      - net-tools
      - policycoreutils-python
      - procps-ng
      - psmisc
      - screen
      - strace
      - sysstat
      - tzdata
      - usbutils
      - vim
      - wget
      - "{{python_firewall_package}}"
  when: base_packages is undefined
  tags:
    - access_setup

- name: add systemd-networkd to base packages (CentOS)
  set_fact:
    base_packages: "{{ base_packages }} + [ 'systemd-networkd' ]"
  when: >
    network_manager is defined and network_manager == "networkd"
    and ansible_distribution == "CentOS"
  tags:
    - access_setup

- name: add HP SPP packages
  set_fact:
    base_packages: "{{ base_packages }} + {{ hp_packages }}"
  when: >
    hp_spp_repository is defined
    and server_type is defined and server_type == "proliant"

- name: set unwanted packages
  set_fact:
    unwanted_packages:
      - chrony
  when: unwanted_packages is undefined
  tags:
    - access_setup

- name: expand package list for bare metal servers
  set_fact:
    base_packages: "{{ base_packages + bare_metal_packages }}"
  when: ansible_virtualization_role == "host"
  tags:
    - access_setup

- name: append extra packages
  set_fact:
    base_packages: "{{ base_packages + redhat_extra_packages }}"
  when: redhat_extra_packages is defined
  tags:
    - access_setup

- name: Get rid of unwanted packages (dnf)
  dnf:
    name: "{{ unwanted_packages }}"
    state: absent
  when: ansible_pkg_mgr == "dnf"

- name: Get rid of unwanted packages (yum)
  yum:
    name: "{{ unwanted_packages }}"
    state: absent
  when: ansible_pkg_mgr == "yum"

- name: Install base packages (dnf)
  dnf:
    name: "{{ base_packages }}"
    state: present
  when: ansible_pkg_mgr == "dnf"
  tags:
    - access_setup

- name: Install base packages (yum)
  yum:
    name: "{{ base_packages }}"
    state: present
  when: ansible_pkg_mgr == "yum"
  tags:
    - access_setup

- name: configure static network interfaces (NM)
  template:
    src: ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{item.key}}"
  with_dict: "{{network_nodes[inventory_hostname].networks |default({})}}"
  when: >
    item.value.static is defined and item.value.static == True
    and network_manager is undefined or
    (network_manager is defined and network_manager == "networkmanager")
  tags:
    - access_setup

- name: disable NetworkManager
  service: name=NetworkManager enabled=no
  when: network_manager is defined and network_manager != "networkmanager"
  notify:
    - stop NetworkManager
  tags:
    - access_setup
  # NetworkManager may not be availeble on all images - it's probably safe to
  # ignore the error here as even a still running network manager won't
  # break networking in many cases
  ignore_errors: True
