# python3 on OS X per default only is a stub pointing to xcode CLI. Make sure
# proper python3 gets installed on bootstrap.
- name: check xcode-select path
  command: xcode-select -p
  ignore_errors: true
  changed_when: false
  register: __xcode_select_p
  tags:
    - base_config
    - access_setup

- name: prepare xcode CLI install
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  when: >
    __xcode_select_p.rc != 0
  tags:
    - base_config
    - access_setup

- name: register xcode CLI product name
  shell: >
    set -o pipefail;
    softwareupdate -l | grep "\*.*Command Line Tools for Xcode" | sort | tail -n 1 | sed 's/^[^C]* //'
  args:
    executable: /bin/bash
  register: __cli_product
  when: >
    __xcode_select_p.rc != 0
  tags:
    - base_config
    - access_setup

- name: install xcode CLI
  command: softwareupdate -i "{{__cli_product.stdout}}"
  register: __result
  failed_when: >
    __result.rc != 0 or
    'Error installing updates.' in __result.stdout
  when: >
    __xcode_select_p.rc != 0
  tags:
    - base_config
    - access_setup

- name: check installed packages
  command: pkgutil --pkgs
  register: __darwin_installed_pkgs
  tags:
    - base_config
    - access_setup
  changed_when: false

- name: install rosetta
  command: softwareupdate --install-rosetta --agree-to-license
  when: >
    ansible_machine == 'arm64' and
    "com.apple.pkg.RosettaUpdateAuto" not in __darwin_installed_pkgs.stdout and
    (install_rosetta is undefined or
     install_rosetta != false)

- name: install homebrew
  include_role:
    name: data-utilities
    tasks_from: install_homebrew
  when: >
    install_homebrew is undefined or
    install_homebrew != false

- ansible.builtin.include_role:
    name: data-utilities
    tasks_from: _homebrew_packages
  when: >
    ansible_version.full is version('2.10', '>=')

- ansible.builtin.include_role:
    name: data-utilities
    tasks_from: _homebrew_packages_legacy
  when: >
    ansible_version.full is version('2.9', '>=') and
    ansible_version.full is version('2.10', '<')

- name: install XIP installers
  include_tasks: install_xip.yml
  with_dict: "{{xip_installers}}"
  loop_control:
    loop_var: _installer
  when: >
    xip_installers is defined
