# note: deletion of old certificates is currently not supported
- name: install additional CA certificates
  tags:
    - access_setup
  copy:
    src: "{{item}}"
    dest: "/etc/pki/ca-trust/source/anchors/{{item}}"
  with_items: "{{ca_certificates|default({})}}"

# this would be better tied to actually changing CA files, but handlers
# only run at the end, which would be too late here. Given that it returns
# very quickly it's not worth the effort to check for changes.
- name: refresh CA trust
  shell: /usr/bin/update-ca-trust
  tags:
    - access_setup

- set_fact:
    centos_repositories: {}
  when: centos_repositories is undefined
  tags:
    - access_setup

- set_fact:
    epel_repositories: {}
  when: epel_repositories is undefined
  tags:
    - access_setup

# media, sources, vault and debuginfo repositories are not provided by us
# enabled repositories are configured through centos_repositories. Subkeys
# are:
#
# - plus
# - cr
# - fasttrack
# - sclo
# - sclo_rh
#
# example:
# centos_repositories
#   sclo: 1
#   sclo_rh: 1
- name: configure dist repos (CentOS)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-fasttrack.repo
    - CentOS-SCLo-scl.repo
    - CentOS-SCLo-scl-rh.repo
  when: ansible_distribution == "CentOS" and centos_mirror is defined
  tags:
    - access_setup

- name: configure epel repos (CentOS)
  template:
    src: "{{item}}.j2"
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    mode: 0644
  with_items:
    - epel.repo
    - epel-testing.repo
  when: ansible_distribution == "CentOS" and epel_mirror is defined
  tags:
    - access_setup

- name: configure fastest_mirror (CentOS)
  template:
    src: yum_fastestmirror.conf.j2
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    owner: root
    mode: 0644
  when: ansible_distribution == "CentOS" and epel_mirror is defined
  tags:
    - access_setup

- name: add additional RPM repositories
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/{{item.key}}.repo
    owner: root
    mode: 0644
  with_dict: "{{ rpm_repos }}"
  when: rpm_repos is defined

- name: add SPP repository
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/hp-spp.repo
    owner: root
    mode: 0644
  with_dict: { hp_spp: { baseurl: '{{hp_spp_repository}}', description: "HP SPP" }}
  when: >
    hp_spp_repository is defined
    and server_type is defined and server_type == "proliant"

- name: configure dnf
  template:
    src: dnf.conf.j2
    dest: /etc/dnf/dnf.conf
    owner: root
    mode: 0755
  tags:
    - access_setup
  when: >
    proxy_host is defined and skip_proxy is undefined
    and ansible_pkg_mgr == "dnf"

- name: configure python-firewall package (default)
  set_fact:
    python_firewall_package: python-firewall

- name: configure python-firewall package (Fedora >= 29)
  set_fact:
    python_firewall_package: python3-firewall
  when:
    ansible_distribution == 'Fedora' and ansible_distribution_version|int >= 29

- name: set basic packages
  set_fact:
    bare_metal_packages:
      - lvm2
      - ntp
      - ipmitool
      - dmidecode
      - nmap
      - lm_sensors
      - lsof
      - hdparm
      - smartmontools
    base_packages:
      - bash-completion
      - bzip2
      - curl
      - ca-certificates
      - firewalld
      - iotop
      - iproute
      - jq
      - net-tools
      - procps-ng
      - psmisc
      - screen
      - strace
      - tzdata
      - usbutils
      - vim
      - wget
      - policycoreutils-python
      - "{{python_firewall_package}}"
  when: base_packages is undefined

- name: add systemd-networkd to base packages (CentOS)
  set_fact:
    base_packages: "{{ base_packages }} + [ 'systemd-networkd' ]"
  when: >
    network_manager is defined and network_manager == "networkd"
  when: ansible_distribution == "CentOS"

- name: set unwanted packages
  set_fact:
    unwanted_packages:
      - chrony
  when: unwanted_packages is undefined

- name: expand package list for bare metal servers
  set_fact:
    base_packages: "{{ base_packages + bare_metal_packages }}"
  when: ansible_virtualization_role == "host"

- name: append extra packages
  set_fact:
    base_packages: "{{ base_packages + redhat_extra_packages }}"
  when: redhat_extra_packages is defined

- name: Get rid of unwanted packages (dnf)
  dnf:
    name: "{{ unwanted_packages }}"
    state: absent
  when: ansible_pkg_mgr == "dnf"

- name: Get rid of unwanted packages (yum)
  yum:
    name: "{{ unwanted_packages }}"
    state: absent
  when: ansible_pkg_mgr == "yum"

- name: Install base packages (dnf)
  dnf:
    name: "{{ base_packages }}"
    state: present
  when: ansible_pkg_mgr == "dnf"

- name: Install base packages (yum)
  yum:
    name: "{{ base_packages }}"
    state: present
  when: ansible_pkg_mgr == "yum"

- name: configure static network interfaces (NM)
  template:
    src: ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{item.key}}"
  with_dict: "{{network_nodes[inventory_hostname].networks |default({})}}"
  when: >
    item.value.static is defined and item.value.static == True
    and network_manager is undefined or
    (network_manager is defined and network_manager == "networkmanager")
  tags:
    - access_setup

- name: disable NetworkManager
  service: name=NetworkManager enabled=no
  when: network_manager is defined and network_manager != "networkmanager"
  notify:
    - stop NetworkManager
  tags:
    - access_setup
  # NetworkManager may not be availeble on all images - it's probably safe to
  # ignore the error here as even a still running network manager won't
  # break networking in many cases
  ignore_errors: True
