- name: add container configuration
  tags:
    - base_config
  template:
    src: "{{__conf}}.j2"
    dest: "/etc/containers/{{__conf}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - registries.conf
    - storage.conf
  loop_control:
    loop_var: __conf
