- set_fact:
    default_passdb_available: False
    is_wsl: False
  tags:
    - base_config
    - access_setup

- set_fact: host_timezone=Europe/Helsinki
  when: host_timezone is undefined
  tags:
    - base_config
    - access_setup
# see: https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)?redirectedfrom=MSDN
- set_fact: host_timezone_win="FLE Standard Time"
  when: host_timezone_win is undefined
  tags:
    - base_config
    - access_setup
- set_fact: adm_uid=10000
  when: adm_uid is undefined
  tags:
    - base_config
    - access_setup
- set_fact: adm_gid=10000
  when: adm_gid is undefined
  tags:
    - base_config
    - access_setup
- set_fact: adm_user=management
  when: adm_user is undefined
  tags:
    - base_config
    - access_setup
- set_fact: adm_group=management
  when: adm_group is undefined
  tags:
    - base_config
    - access_setup
- set_fact: firewalld_available=False
  when: firewalld_available is undefined
  tags:
    - base_config
    - access_setup
- set_fact:
    server_type: "proliant"
    server_model: "{{ ansible_product_name.split(' ')[1] | lower }}"
    server_gen: "{{ ansible_product_name.split(' ')[2] | int }}"
  when: ansible_product_name.split(" ")[0] | lower == "proliant"
