- set_fact: host_timezone=Europe/Helsinki
  when: host_timezone is undefined
  tags:
    - base_config
    - access_setup
# see: https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)?redirectedfrom=MSDN
- set_fact: host_timezone_win="FLE Standard Time"
  when: host_timezone_win is undefined
  tags:
    - base_config
    - access_setup

- set_fact:
    ansible_product_name: "Undefined. Ansible bug?"
  when: ansible_product_name == None

- set_fact:
    server_type: "proliant"
    server_model: "{{ ansible_product_name.split(' ')[1] | lower }}"
    server_gen: "{{ ansible_product_name.split(' ')[2] | int }}"
  when: ansible_product_name.split(" ")[0] | lower == "proliant"
