- name: manage firewalld rich rule ({{rule.key}})
  firewalld:
    zone: "{{entry[0]}}"
    rich_rule: "{{entry[1]}}"
    permanent: true
    state: "{{rule.value.state|default('enabled')}}"
    immediate: true
  with_nested:
    - "{{ rule.value.zones|default([rule.value.zone]) }}"
    - "{{ rule.value.rules|default([rule.value.rule]) }}"
  loop_control:
    loop_var: entry
