- name: manage firewalld source ({{rule.key}})
  firewalld:
    zone: "{{entry[0]}}"
    source: "{{entry[1]}}"
    permanent: true
    state: "{{rule.value.state|default('enabled')}}"
    immediate: true
  with_nested:
    - "{{ rule.value.zones|default([rule.value.zone]) }}"
    - "{{ rule.value.sources|default([rule.value.source]) }}"
  loop_control:
    loop_var: entry