- name: manage firewalld service ({{rule.key}})
  firewalld:
    zone: "{{entry[0]}}"
    service: "{{entry[1]}}"
    permanent: true
    state: "{{rule.value.state|default('enabled')}}"
    immediate: true
  with_nested:
    - "{{ rule.value.zones|default([rule.value.zone]) }}"
    - "{{ rule.value.services|default([rule.value.service]) }}"
  loop_control:
    loop_var: entry
