- set_fact:
    windows_script_directory: 'c:\ci'
  when: windows_script_directory is undefined
  tags:
    - base_config
    - access_setup

# windows creates the home directory not on user creation, but first
# logon -> creating users and directly trying to add ssh keys can be
# problematic. Using a separate key directory solves that - but also
# creates a lot of problems with permissions. Just create the directory
# in case it is required.
- set_fact:
     windows_ssh_key_directory: '%ProgramData%\ssh_keys'
  when: windows_ssh_key_directory is undefined
  tags:
    - base_config
    - access_setup

# subdirectory made available in windows search path
- set_fact:
    windows_script_directory_bin: '{{windows_script_directory}}\bin'
  tags:
    - base_config
    - access_setup

- set_fact:
    windows_temp_directory: 'c:\temp'
  when: windows_temp_directory is undefined
  tags:
    - base_config
    - access_setup

# https://support.microsoft.com/en-us/help/942817/how-to-change-the-remote-uac-localaccounttokenfilterpolicy-registry-se
# Makes sure remote sessions of users in the admin group have admin privileges
- name: configure LocalAccountTokenFilterPolicy
  win_regedit:
    path: hklm:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\system
    name: LocalAccountTokenFilterPolicy
    data: 1
    type: dword
  tags:
    - base_config
    - access_setup

# This is in a separate file as there are a lot of keys, and we probably still
# didn't get all of them
- name: configure TLS
  include_tasks: win_configure_tls.yml

- name: set connection profiles to private
  win_command: "powershell.exe Set-NetConnectionProfile -NetworkCategory Private"
  register: wincmd_status
  changed_when: wincmd_status.rc != 0
  tags:
    - base_config
    - access_setup

- name: make sure winrm is running
  win_command: "winrm.cmd quickconfig -q"
  register: wincmd_status
  changed_when: wincmd_status.rc != 0
  tags:
    - base_config
    - access_setup

- name: configure winrm for delayed startup
  win_service:
    name: WinRM
    start_mode: delayed
  tags:
    - base_config
    - access_setup

- name: check program files folder path
  win_command: powershell.exe -Command "[environment]::getfolderpath('Programfiles')"
  register: wincmd_status
  changed_when: false
  tags:
    - base_config
    - access_setup

- name: register program files folder path ({{wincmd_status}})
  set_fact:
    program_files_path: "{{wincmd_status.stdout_lines[0]}}"
  tags:
    - base_config
    - access_setup

- name: make sure windows temp directory exists
  win_file:
    path: "{{windows_temp_directory}}"
    state: directory
  tags:
    - base_config
    - access_setup

- name: make sure windows script directory exists
  win_file:
    path: "{{windows_script_directory}}"
    state: directory
  tags:
    - base_config
    - access_setup

- name: make sure windows script directory bin exists
  win_file:
    path: "{{windows_script_directory_bin}}"
    state: directory
  tags:
    - base_config
    - access_setup

- name: make sure windows script bin directory is in path
  win_path:
    elements:
      - "{{windows_script_directory_bin}}"
  tags:
    - base_config
    - access_setup

- name: make sure SSH key directory exists ({{windows_ssh_key_directory}})
  win_file:
    path: "{{windows_ssh_key_directory}}"
    state: directory
  tags:
    - access_setup
    - base_config

- include: manage_adm_user_win.yml
  tags:
    - base_config
    - access_setup

- ansible.builtin.include_role:
    name: data-utilities
    tasks_from: manage_time
  tags:
    - base_config

# TODO: ICMP should be enabled per default for Windows
#- name: configure ICMP in firewall

- ansible.builtin.include_role:
    name: data-utilities
    tasks_from: manage_hostname

# this doesn't take proxies, .. into account
# the assumption is that there's a local, controlled mirror
# with all those archives
# the installers are still downloaded for uninstalls - some components
# need the original installer for a clean uninstall
- name: download windows installers
  win_get_url:
    url: "{{item.value.url}}"
    dest: "{{windows_temp_directory}}\\{{item.key}}"
  with_dict: "{{windows_installers|default({})}}"
  when: >
    (item.value.state is undefined or item.value.state == 'present') and
    item.value.url is defined

# TODO: check checksums using win_stat, if available; extract zips
- name: remove windows installers
  with_dict: "{{windows_installers|default({})}}"
  win_package:
    product_id: "{{item.value.product_id}}"
    state: absent
  when: >
    (item.value.state is defined and item.value.state == 'absent') and
    item.value.product_id is defined and
    item.value.uninstall_arguments is undefined

- name: remove windows installers (custom arguments)
  with_dict: "{{windows_installers|default({})}}"
  win_package:
    product_id: "{{item.value.product_id}}"
    state: absent
    arguments: "{{item.value.uninstall_arguments}}"
    path: "{{item.value.path|default(windows_temp_directory)}}\\{{item.key}}"
  when: >
    (item.value.state is defined and item.value.state == 'absent') and
    item.value.product_id is defined and
    item.value.uninstall_arguments is defined

# To get the product ID, for
# - MSI: msiinfo suminfo <msi-file> (from wix/msitools); sometimes wrong
# - general: install the package on a temp system, open powershell,
#   cd HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall, and
#   check contents with ls
# - get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
# - Get-ItemProperty HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* |Select-Object DisplayName, DisplayVersion, Publisher, InstallDate|Format-Table -AutoSize
# - Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\* |Select-Object DisplayName, DisplayVersion, Publisher, InstallDate|Format-Table -AutoSize

- name: install windows installers
  with_dict: "{{windows_installers|default({})}}"
  win_package:
    product_id: "{{item.value.product_id}}"
    path: "{{item.value.path|default(windows_temp_directory)}}\\{{item.key}}"
    arguments: "{{item.value.arguments|default('')}}"
  when: >
    (item.value.state is undefined or item.value.state == 'present') and
    (item.value.url is defined or item.value.path is defined) and
    item.value.product_id is defined

- include_tasks: win_unpack_zips.yml
  with_dict: "{{windows_installers|default({})}}"
  loop_control:
    loop_var: _installer
  when: >
    (_installer.value.state is undefined or _installer.value.state == 'present') and
    (_installer.value.url is defined or _installer.value.path is defined) and
    _installer.value.product_id is undefined and
    _installer.value.dest is defined and
    _installer.key.endswith(".zip")

- name: add extra windows paths
  with_dict: "{{windows_extra_paths|default({})}}"
  win_path:
    elements:
      - "{{ item.value.path }}"

# for whatever reason windows insists on broken store reference entries in
# some cases -> nuke those
- include_tasks: win_remove_applinks.yml
  with_dict: "{{windows_installers|default({})}}"
  when: >
    (item.value.state is undefined or item.value.state == 'present') and
    item.value.url is defined and item.value.product_id is defined and
    item.value.appdata_orphans is defined

- name: create local users (without password)
  win_user:
    account_disabled: "{{item.value.disabled|default('no')}}"
    name: "{{item.key}}"
    fullname: "{{item.value.fullname|default(item.key)}}"
    description: "{{item.value.comment|default('Created by ansible')}}"
    groups: "{{item.value.groups|default('')}}"
    state: "{{item.value.state|default('present')}}"
    password_expired: "{{item.value.password_expired|default('no')}}"
    password_never_expires: "{{item.value.password_never_expires|default('no')}}"
    user_cannot_change_password: "{{item.value.user_cannot_change_password|default('yes')}}"
  with_dict: "{{win_users}}"
  when: win_users is defined and item.value.passdb_entry is undefined
  tags:
    - base_config
    - access_setup

- name: create local users (with password)
  win_user:
    account_disabled: "{{item.value.disabled|default('no')}}"
    name: "{{item.key}}"
    fullname: "{{item.value.fullname|default(item.key)}}"
    description: "{{item.value.comment|default('Created by ansible')}}"
    groups: "{{item.value.groups|default('')}}"
    state: "{{item.value.state|default('present')}}"
    password: "{{lookup(passdb, item.value.passdb_entry)}}"
    password_expired: "{{item.value.password_expired|default('no')}}"
    password_never_expires: "{{item.value.password_never_expires|default('no')}}"
    user_cannot_change_password: "{{item.value.user_cannot_change_password|default('yes')}}"
  with_dict: "{{win_users}}"
  when: win_users is defined and item.value.passdb_entry is defined
  tags:
    - base_config
    - access_setup

- include_tasks: manage_wsl.yml
  when: wsl_distributions is defined
