# this is the entry point to include when trying to perform access setup
# through delegates (like for container deployment). This includes only
# tasks which correctly handle delegation, and special care needs to be
# taken not to break that when touching files included here.
#
# So far only suse is supported.
#
# Delegated access setup only does the following steps:
# - configure core repositories
# - install basic packages
# - create and configure management user

- debug: msg="Running for {{delegate_hostname|default(inventory_hostname)}}"
  when: >
    debug_delegates is defined

- name: check provisioning marker
  stat:
    path: "/.provisioning-needed"
  register: marker

- debug:
    msg:
      - "Step 1:"
      - "{{hostvars[delegate_hostname].base_packages|default('unset')}}"
  when: >
    debug_delegates is defined and
    delegate_hostname is defined

- name: [delegate] include distribution specific tasks
  include_tasks: "{{ ansible_os_family }}_basic_setup.yml"
  when: ansible_os_family == "Debian" or ansible_os_family == "Suse" or ansible_os_family == "RedHat"
  tags:
    - base_config
    - access_setup

- name: [delegate] include distribution specific tasks (MicroOS)
  include_tasks: "basic_host_Suse.yml"
  when: >
    ansible_os_family == "openSUSE MicroOS"
  tags:
    - base_config
    - access_setup

- debug:
    msg:
      - "Step 4:"
      - "{{hostvars[delegate_hostname].base_packages|default('unset')}}"
  when: delegate_hostname is defined

# note: this is currently only fully supported with suse based distributions.
#       other distributions most likely need extra work in data-utilities
- name: [delegate] Install base packages
  include_role:
    name: data-utilities
    tasks_from: install_packages
  vars:
    role_packages: "{{ hostvars[delegate_hostname|default(inventory_hostname)].base_packages }}"
    update_repo_cache: true
  when: >
    ansible_os_family == "Debian" or ansible_os_family == "RedHat" or
    ansible_os_family == "Suse" or ansible_os_family == "openSUSE MicroOS"
  tags:
    - base_config
    - access_setup

- include_tasks: manage_adm_user.yml
