- name: verify ansible version
  assert:
    that: "ansible_version.full is version_compare('2.8', '>=')"
    msg: >
      "Minimum ansible version required for running this is 2.8"
  tags:
    - base_config
    - access_setup

- name: merge local network nodes into global one
  set_fact:
    network_nodes: "{{ {} | combine(network_nodes, local_network_nodes, recursive=True) }}"
  when: local_network_nodes is defined

- name: set default password store
  set_fact:
    passdb: passwordstore
  when: passdb is undefined

- name: set default password length
  set_fact:
    passdb_password_length: 20
  when: passdb_password_length is undefined

- name: set default for password creation
  set_fact:
    passdb_password_create: True
  when: passdb_password_create is undefined

- name: set passdb extra arguments
  set_fact:
    passdb_extra_arg: " create={{passdb_password_create}} length={{passdb_password_length}}"

- name: include main tasks for non-Windows
  include_tasks: main_default.yml
  tags:
    - base_config
    - access_setup
  when: ansible_os_family != "Windows"

- name: include main tasks for windows
  include_tasks: main_windows.yml
  tags:
    - base_config
    - access_setup
  when: ansible_os_family == "Windows"