- name: add {{_repository.value.name|default(_repository.key)}}
  template:
    src: "rpm-repo.j2"
    dest: /etc/yum.repos.d/{{_repository.value.name|default(_repository.key)}}.repo
    owner: root
    mode: 0644
  when: >
    _repository.value.state is undefined or
    _repository.value.state == "present"
  tags:
    - access_setup

- name: remove {{_repository.value.name|default(_repository.key)}}
  file:
    path: /etc/yum.repos.d/{{_repository.value.name|default(_repository.key)}}.repo
    state: absent
  when: >
    _repository.value.state is defined and
    _repository.value.state == "absent"
  tags:
    - access_setup