- name: delete old profile.d files
  file:
    state: absent
    path: "/etc/profile.d/{{_file}}"
  when: removed_profiled_files is defined
  with_items: "{{removed_profiled_files}}"
  loop_control:
    loop_var: _file

- name: add profiled files
  template:
    src: "{{_file}}.j2"
    dest: "/etc/profile.d/{{_file}}"
    mode: 0644
  when: profiled_files is defined
  with_items: "{{profiled_files}}"
  loop_control:
    loop_var: _file
