- name: include additional handlers
  include_tasks: "handlers/{{item}}.yml"
  with_items: "{{basic_host_extra_handlers}}"
  when: basic_host_extra_handlers is defined

- name: restart sshd
  service: name=sshd state=restarted
  ignore_errors: yes

- name: update certificates
  command: /usr/sbin/update-ca-certificates

- name: restart networkd
  systemd: name=systemd-networkd state=restarted daemon_reload=yes
  when: ansible_service_mgr == 'systemd'

- name: restart logind
  systemd: name=systemd-logind state=restarted
  when: ansible_service_mgr == 'systemd'

- name: restart journald
  systemd: name=systemd-logind state=restarted
  when: ansible_service_mgr == 'systemd'

- name: stop NetworkManager
  systemd: name=NetworkManager state=stopped daemon_reload=yes
  when: ansible_service_mgr == 'systemd'

- name: restart rbdmap
  systemd: name=rbdmap
  when: ansible_service_mgr == 'systemd'

- name: restart wpa_supplicant
  systemd:
    name: "wpa_supplicant@{{__iface}}.service"
    enabled: yes
    state: restarted
  with_items: "{{__wpa_supplicant_ifaces}}"
  loop_control:
    loop_var: __iface
  when: >
    network_manager is defined and network_manager == "networkd" and
    __wpa_supplicant_ifaces is defined and
    __wpa_supplicant_ifaces|count >= 1
