- name: restart sshd
  service: name=sshd state=restarted
  ignore_errors: yes

- name: update certificates
  command: /usr/sbin/update-ca-certificates

- name: restart networkd
  systemd: name=systemd-networkd state=restarted daemon_reload=yes

- name: stop NetworkManager
  systemd: name=NetworkManager state=stopped daemon_reload=yes